### Create a new user
POST http://localhost:3000/auth/signup
Content-type: application/json

{
    "email": "techie@gmail.com",
    "password": "techiePW-2"
}

### Authenticate a user
POST http://localhost:3000/auth/signin
Content-type: application/json

{
    "email": "techie@gmail.com",
    "password": "techiePW-2"
}

### Find a particular user with a given id
GET http://localhost:3000/auth/1

### Find all users with a given email address
GET http://localhost:3000/auth?email=moussakalamamzat@gmail.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/20

### Update a user with a given id
PATCH http://localhost:3000/auth/1
Content-type: application/json

{
    "password": "newpassword"
}